<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

	
    <ItemGroup>
		<!--<ProjectReference Include="..\UniMDB.Domain\UniMDB.Domain.csproj" />-->
	    <ProjectReference Include="..\UniMDB.Infrastructure\UniMDB.Infrastructure.csproj" />
	</ItemGroup>


</Project>
