@UniMDB.API_HostAddress = http://localhost:5254

GET {{UniMDB.API_HostAddress}}/api/User/get/1
Accept: application/json

POST {{UniMDB.API_HostAddress}}/api/User/add
Accept: application/json

PUT {{UniMDB.API_HostAddress}}/api/User/update
Accept: application/json

DELETE {{UniMDB.API_HostAddress}}/api/User/delete/id
Accept: application/json


###
