// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniMDB.Infrastructure.Data;

#nullable disable

namespace UniMDB.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UniMDB.Domain.Entities.Review", b =>
                {
                    b.Property<uint>("id_review")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("comment")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("id_movie_mdb")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<uint>("id_review_user")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("review")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("id_review");

                    b.HasIndex("id_review_user");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("UniMDB.Domain.Entities.User", b =>
                {
                    b.Property<uint>("id_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_user");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UniMDB.Domain.Entities.Review", b =>
                {
                    b.HasOne("UniMDB.Domain.Entities.User", "user")
                        .WithMany("reviews")
                        .HasForeignKey("id_review_user");

                    b.Navigation("user");
                });

            modelBuilder.Entity("UniMDB.Domain.Entities.User", b =>
                {
                    b.Navigation("reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
